apiVersion: v1
data:
  secretkey: WVNuRER1N1daZHNEMnhyVzFyV0NObExCNHozUi9KMnczeDNwSmJFRFNhTTEvU041TVpyMjBwK2dsWTV3eURwYQpKdVB2RmtGcUc2b3l5OE5TWmJHVjdyQnY3RDNMN2tZVGNCaTRTb0tzOXpDZFVlSmlsaDIzMUwxYXBXWVN2bzRBCjRpZ0MvejNreDRLQ1RocG1aazlOVE5ibUFVVjIzNmZKWlpPYmFRS3VUM3M9
kind: Secret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
