kind: Kustomization
namespace: flux-system
resources:
  - helm_release.yaml
configMapGenerator:
  - name: my-ingressnginx
    files:
      - values.yaml=my-nginxingress.yaml
configurations:
  - kustomizeconfig.yaml
