apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: demo-mysqldb
  namespace: flux-system
spec:
  chart:
    spec:
      chart: mysql
      sourceRef:
        kind: HelmRepository
        name: helmrepo-private
      version: 1.6.9
  install: 
    disableWait: true
  upgrade:
    disableWait: true
  interval: 30s
  releaseName: demo-mysqldb
  targetNamespace: demo-webapp
  valuesFrom:
    - kind: ConfigMap
      name: mysqlvalues
