apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pv-www-claim
    namespace: demo-webapp
spec:
    storageClassName: standard
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 100Mi
