apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: flux-system
spec:
  chart:
    spec:
      chart: jenkins
      sourceRef:
        kind: HelmRepository
        name: helmrepo-jenkins 
      version: 5.4.1
  install: 
     disableWait: true
  upgrade:
     disableWait: true
  interval: 30s
  releaseName: jenkins
  targetNamespace: jenkins
  valuesFrom:
    - kind: ConfigMap
      name: my-jenkins
