users:
  - default
  - name: vmadmin
    sudo:  ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC3gJPgIEpbrsHecVEM1lPKEqkcr1+AmfYal11mSX8WFfKa2Y8LdzxRbRWQtWnczzYkw26CMgst416sficXRc5izqIdkBF82vzGmtgxq+FhSK+s7VOy7OKVNLUWRnKIaJMc0f9/m/0hEfsMslfGBQIz7gjpuMv8I2UWfuG8QB6m8TGzffaHI9d9es7KZA3W/jwEByy5j2dCoY44yDdG7I8cnPOzX2EqN9uq0hiEetikbJtyxWMuK66ELUuHkxeHE2fQ1kxj7y1fz3Ej5wyIvQ0B/Di86v91sHmzTZVAjY6IsBirzflzpIo5FXnC6t0T+tGCgMnpGLXu1gJdNFlxCzQW79JJoI6W8AEaTMl0RnFOJgtvTEGFY6Egf6yvh1vQOpEQGTrrPaLkWHChak7xma9dW0yDDXtnnrr+aSwnFUG7x+iGFbY/o4vO48bpqCP0Y8j6xE4ANTrd/3i4uabxnYQjTkH0NiixRS7tLIHgesp9ObqGYCpDDLn7xGtbSdX+Q2c= vmadmin
