---
# Creates vmadmin keypair that will be used to log into the Multipass VMs
# and the cloud-init file use when create the VMs.
# Deletes any existing keys and cloud-init file.
- name: Delete any existing public and private key
  tags: install
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - ./roles/install-vm/tasks/user_key
    - ./roles/install-vm/tasks/user_key.pub
- name: Create vmadmin key-pair
  tags: install
  shell: ssh-keygen -C vmadmin -N "" -f ./roles/install-vm/tasks/user_key
  delegate_to: localhost
- name: Delete any existing cloud-init file
  tags: install
  file:
    path: cloud-init.yaml
    state: absent
- name: Create cloud-init file inserting the public key
  tags: install
  template:
    src: cloud-init-template.j2
    dest: ./roles/install-vm/tasks/cloud-init.yaml
  delegate_to: localhost
  vars:
    public_key: "{{lookup('file', './roles/install-vm/tasks/user_key.pub')}}"
