---
# Deletes any existing Multipass VM with the supplied name, then creates
# a new VM with the supplied name is created with the supplied parameters.
# Prerequisites:
# A SSH keypair that will be used as one option to log into the new VM must exist.
# A cloud-init configuration file named "cloud-init.yaml" that will be used
# when creating the new VM must exist.
# Variables:
# vmname - Name of the VM that is to be create.
# vmcreationparams - Parameters that will be used when creating the new VM with Multipass.
- name: Log VM creation start
  debug:
    msg: "About to create VM {{ vmname }}..."
  tags: install
- name: Delete existing VM
  shell: |
    multipass info {{ vmname }} > /dev/null 2> /dev/null
    if [ $? -eq 0 ]; then
      multipass delete {{ vmname }}
      multipass purge
    fi
  delegate_to: localhost
  tags: install

- name: Create new VM
  shell: multipass launch --name {{ vmname }} --cloud-init ./roles/install-vm/tasks/cloud-init.yaml {{ vmcreationparams }}
  delegate_to: localhost
  tags: install

- name: Register the VM_IP
  shell: multipass list | grep  {{ vmname }} | awk  '{print $3}'
  register: vm_ip
  tags: install

- name: Register the VM_NAME
  shell: multipass list | grep  {{ vmname }} | awk  '{print $1}'
  register: vm_name
  tags: install

- set_fact:
   VM_IP: "{{vm_ip}}"
   VM_NAME: "{{vm_name}}"

- name: Log VM creation completion
  debug:
    msg: "Finished creating VM {{ vmname }}."
  tags: install
